name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: latest
      - run: npm ci 
      - run: npm run lint
      - run: npm test
